baseurl = "http://blog.ralch.com"
languageCode = "en-us"
title = "Software adventures and thoughts"
theme = "hyde"

[Author]
	name = "Svett Ralchev"

[Permalinks]
 post = "/:year/:month/:filename/"
 tutorials = "/:filename/"

[params]
 info = "http://www.ralch.com"
 twitter = "https://twitter.com/ralch"
 github = "https://github.com/svett"
 linkedin = "http://uk.linkedin.com/in/svettralchev"
 disqus = "ralch"
 googletrackingid = "UA-62134307-2"
 domain = "blog.ralch.com"


